public static class Namer 
{ 

    public static string nameSurah(int a) =>
    a switch
    {
        1 => "Fotiha",
        2 => "Baqara",
        3 => "Oli_Imron",
        4 => "Niso",
        5 => "Moida",
        6 => "Anom",
        7 => "Aarof",
        8 => "Anfol",
        9 => "Tavba",
        10 => "Yunus",
        11 => "Hud",
        12 => "Yusuf",
        13 => "Raad",
        14 => "Ibrohim",
        15 => "Hijr",
        16 => "Nahl",
        17 => "Isro",
        18 => "Kahf",   
        19 => "Maryam",
        20 => "Toha",
        21 => "Anbiyo",
        22 => "Haj",
        23 => "Muminun",
        24 => "Nur",
        25 => "Furqon",
        26 => "Shuaro",
        27 => "Naml",
        28 => "Qasas",
        29 => "Ankabut",
        30 => "Rum",
        31 => "Luqmon",
        32 => "Sajda",
        33 => "Ahzob",
        34 => "Saba",
        35 => "Fotir",
        36 => "Yosin",
        37 => "Soffat",
        38 => "Sod",
        39 => "Zumar",
        40 => "Gofir",
        41 => "Fussilat",
        42 => "Shoro",
        43 => "Zuxruf",
        44 => "Duxon",
        45 => "Josiya",
        
        _ => "Nomalum",
};
} 